### ISSUE TITLE
Api key

### ISSUE THREAD

**Issue by faruktoptas** [eneserdogan/trino#2]
Your Google Translate API Key is sensitive data and you share it publicly here: https://github.com/eneserdogan/trino/blob/master/index.js#L5

**Comment by eneserdogan** [comment]
Yes i know it, the reason is i did this project as an open source project that people can use it unlimited. The open API key is not problem for me even i can pay if it is necessery. Thats enaugh for me if people can develop something usefull with this key.

Thank you for your feedback!

**Comment by faruktoptas** [comment]
Sensitive data should not be public. Please read:
http://blog.arvidandersson.se/2013/06/10/credentials-in-git-repos
https://help.github.com/articles/removing-sensitive-data-from-a-repository/

**Comment by eneserdogan** [comment]
This is not so sensitive data for me :)

**Comment by faruktoptas** [comment]
ok :)
